[package]
name = "installer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
chrono = "0.4.24"
dirs = "5.0.0"
image = "0.24.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bytes = "1"
async-trait = "0.1.68"
async-recursion = "1.0.4"
futures = "0.3.28"
iced = "0.8.0"
isahc = "1.7.2"
clap = { version = "4.2.1", features = ["derive"] }
