[package]
name = "installer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "s"
lto = "fat"

[dependencies]
base64 = "0.21.0"
chrono = "0.4.24"
dirs = "5.0.0"
image = "0.24.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
async-trait = "0.1.68"
futures = "0.3.28"
isahc = "1.7.2"
clap = { version = "4.2.1", features = ["derive"] }
zip = "0.6.4"
dioxus = { git = "https://github.com/DioxusLabs/dioxus", rev = "9b02b21" }
dioxus-desktop = { git = "https://github.com/DioxusLabs/dioxus", rev = "9b02b21" }
cached = { version = "0.43.0", features = ["redis_async_std"] }
regex = "1.8.1"
