[package]
name = "installer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.0"
reqwest = { version = "0.11.16", features = ["blocking"] }
semver = "1.0.17"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
