name: Rust Appbundle

on: workflow_dispatch

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  CARGO_TERM_COLOR: always

jobs:
  build:
  
    strategy:
      matrix:
        os: [macos-12]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3
    - name: Build
      run: cargo build --verbose
    - name: Build bundle
      run: |
        ./scripts/build-appbundle.sh
    - name: capture build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}
        path: macos_bundle/Installer.app
