name: rust-test-latest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUSTC_WRAPPER: sccache
  SCCACHE_GHA_ENABLED: "true"

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install latest sccache (with GHA support)
      run: |
        curl -L -o sccache.zip https://github.com/mozilla/sccache/releases/download/v0.7.7/sccache-v0.7.7-x86_64-pc-windows-msvc.zip
        tar -xf sccache.zip
        echo "${{ github.workspace }}\\sccache-v0.7.7-x86_64-pc-windows-msvc" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Inject GHA cache env vars
      uses: actions/cache/save@v3
      with:
        path: |
          target
        key: dummy-key-${{ runner.os }}-${{ github.run_id }}
      continue-on-error: true

    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: cargo-registry-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-registry-${{ runner.os }}-

    - name: Cache Cargo git index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: cargo-git-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-git-${{ runner.os }}-

    - name: Build with sccache
      run: cargo build --profile ci --bin wynncraft-overhaul-installer --verbose

    - name: Show sccache stats
      run: sccache --show-stats

    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: wynncraft-installer
        path: target/ci/wynncraft-overhaul-installer.exe
