name: rust-test-latest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  RUSTC_WRAPPER: "sccache"
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install sccache
      run: cargo install sccache

    - name: Cache sccache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/sccache
        key: sccache-windows-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          sccache-windows-

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: cargo-registry-windows-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-registry-windows-

    - name: Cache cargo index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: cargo-git-windows-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-git-windows-

    - name: Build project
      run: cargo build --verbose --release
      env:
        RUSTC_WRAPPER: sccache
        CARGO_TERM_COLOR: always

    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: wynncraft-installer
        path: target/release/wynncraft-overhaul-installer.exe
