name: rust-test-latest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies (Linux)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libglib2.0-dev \
            libgdk-pixbuf-2.0-dev \
            libpango1.0-dev \
            libcairo2-dev \
            libwebkit2gtk-4.1-dev \
            libxdo-dev \
            pkg-config

      - name: Install system dependencies (macOS)
        if: matrix.os == 'macos-12'
        run: |
          brew update
          brew install gtk+3 webkit2gtk pkg-config

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ matrix.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ matrix.os }}-

      - name: Build project
        run: cargo build --verbose --release

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: wynncraft-installer-${{ matrix.os }}
          path: |
            target/release/wynncraft-overhaul-installer${{ matrix.os == 'windows-2022' && '.exe' || '' }}
