name: rust-rest-latest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUSTC_WRAPPER: sccache
  SCCACHE_GHA_ENABLED: "true"

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Setup GitHub-native sccache
      uses: mozilla-actions/sccache-action@v0.0.3

    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: cargo-registry-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-registry-${{ runner.os }}-

    - name: Cache Cargo git index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: cargo-git-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-git-${{ runner.os }}-

    - name: Build release
      run: cargo build --release --verbose

    - name: Show sccache stats
      run: sccache --show-stats

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: wynncraft-installer
        path: target/release/wynncraft-overhaul-installer.exe
