name: rust-test-latest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Cache cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: cargo-windows-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-windows-

    - name: Build project
      run: cargo build --verbose --release

    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: wynncraft-installer-windows
        path: target/release/wynncraft-overhaul-installer.exe
