name: rust-test-latest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install latest sccache (0.8+)
      run: cargo install sccache --force

    - name: Cache sccache
      uses: actions/cache@v3
      with:
        path: ~/.cache/sccache
        key: sccache-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          sccache-${{ runner.os }}-

    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: cargo-registry-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-registry-${{ runner.os }}-

    - name: Cache Cargo git index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: cargo-git-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-git-${{ runner.os }}-

    - name: Build project with CI profile
      run: cargo build --profile ci --bin wynncraft-overhaul-installer --verbose

    - name: Show sccache stats
      run: sccache --show-stats

    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: wynncraft-installer
        path: target/ci/wynncraft-overhaul-installer.exe
