name: rust-test-latest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download prebuilt sccache binary
      run: |
        Invoke-WebRequest https://github.com/mozilla/sccache/releases/download/v0.8.0/sccache-v0.8.0-x86_64-pc-windows-msvc.tar.gz -OutFile sccache.tar.gz
        tar -xzf sccache.tar.gz
        echo "${{ github.workspace }}/sccache-v0.8.0-x86_64-pc-windows-msvc" | Out-File -Append -Encoding ascii $env:GITHUB_PATH

    - name: Cache sccache
      uses: actions/cache@v3
      with:
        path: ~/.cache/sccache
        key: sccache-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          sccache-${{ runner.os }}-

    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: cargo-registry-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-registry-${{ runner.os }}-

    - name: Cache Cargo git index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: cargo-git-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-git-${{ runner.os }}-

    - name: Build with sccache + ci profile
      run: cargo build --profile ci --bin wynncraft-overhaul-installer --verbose
      env:
        RUSTC_WRAPPER: sccache
        CARGO_TERM_COLOR: always
        SCCACHE_GHA_ENABLED: "true"

    - name: Show sccache stats
      run: sccache --show-stats

    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: wynncraft-installer
        path: target/ci/wynncraft-overhaul-installer.exe
