name: Rust-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  CARGO_TERM_COLOR: always

jobs:
  build:
  
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v4
    - name: install dependencies
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc pkg-config libglib2.0-dev libgtk-3-dev libssl-dev libjavascriptcoregtk-4.1-dev libsoup-3.0-dev libwebkit2gtk-4.1-dev libxdo-dev
    - name: Build
      run: cargo build --verbose --release
    - name: Strip debug info
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      run: strip target/release/installer
    - name: capture build artifacts windows
      if: ${{ matrix.os == 'windows-2022' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}
        path: target/release/installer.exe
    - name: capture build artifacts
      if: ${{ matrix.os != 'windows-2022' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}
        path: target/release/installer
