name: rust-test-latest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12, windows-2022]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Linux dependencies
      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc pkg-config \
            libglib2.0-dev libgtk-3-dev libssl-dev \
            libjavascriptcoregtk-4.1-dev libsoup-3.0-dev libwebkit2gtk-4.1-dev

      # macOS dependencies
      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-12'
        run: |
          brew update
          brew install gtk+3 webkit2gtk pkg-config

      # Rust toolchain
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Cache
      - name: Cache cargo registry + target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ matrix.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ matrix.os }}-

      # Build
      - name: Build project
        run: cargo build --verbose --release

      # Strip binaries on Linux/macOS
      - name: Strip binary (Linux/macOS)
        if: matrix.os != 'windows-2022'
        run: strip target/release/wynncraft-overhaul-installer || true

      # Upload artifacts
      - name: Upload artifact (Windows)
        if: matrix.os == 'windows-2022'
        uses: actions/upload-artifact@v4
        with:
          name: wynncraft-installer-windows
          path: target/release/wynncraft-overhaul-installer.exe

      - name: Upload artifact (Linux)
        if: matrix.os == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4
        with:
          name: wynncraft-installer-linux
          path: target/release/wynncraft-overhaul-installer

      - name: Upload artifact (macOS)
        if: matrix.os == 'macos-12'
        uses: actions/upload-artifact@v4
        with:
          name: wynncraft-installer-macos
          path: target/release/wynncraft-overhaul-installer
